apiVersion: v1
kind: Service
metadata:
  name: object-detection-app-service
  labels:
    app: object-detection
    version: v1
spec:
  selector:
    app: object-detection

  ports:
    - port: 80
      targetPort: 8000

  type: LoadBalancer
